### ISSUE TITLE
Nu buttons rendering in modal window

### ISSUE THREAD

**Issue by HarveyEV** [Jako/AjaxUpload#11]
I have a bootstrap modal into which I load a resource with a formit form containing the ajaxupload snippet. However none of the buttons render in the form. When I use a plain resource not loaded in a modal the buttons render fine.

My snippet call is :
`              [[!AjaxUpload?
                &uid=`image`
                &allowedExtensions=`jpg,jpeg,png,gif`
                &thumbX=`75`
                &thumbY=`75`
                &maxFiles=`1`
              ]]`

**Comment by HarveyEV** [comment]
All that renders is the noscript button which is not visible obviously:
`<noscript><input type="file" name="image"/></noscript>`

**Comment by crecorn** [comment]
Are you aware you missing the `` in the snippet?

`[[!AjaxUpload? &uid=`image` &allowedExtensions=`jpg,jpeg,png,gif` &thumbX=`75` &thumbY=`75` &maxFiles=`1` ]]`

**Comment by HarveyEV** [comment]
yeah. Github strips backticks.

**Comment by HarveyEV** [comment]
It appears the js is not being appended to the body when called in a modal window.

**Comment by HarveyEV** [comment]
Yeah I manually loaded the css and js and the buttons are rendering now. Next for the Formit hooks... Thx.
