### ISSUE TITLE
Limited uploads

### ISSUE THREAD

**Issue by crecorn** [Jako/AjaxUpload#12]
I'm using this in an e-commerce site. Every order has an image upload. It won't add any more products. This only happens on products with the upload. This is my snippet:

```
[[!AjaxUpload?
&uid=`image`
&allowedExtensions=`jpg,jpeg,png,gif,mp3,avi,amr`
&thumbX=`75`
&thumbY=`75`
&maxFiles=`999`
&maxFilesizeMb=`50`
]]
```

**Comment by Jako** [comment]
Is this actual?

**Comment by Jako** [comment]
Feel free to reopen it, if it is still valid.
