### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by hugopeek** [Jako/AjaxUpload#16]
I'm getting `Uncaught TypeError: b._isValidFileDrag is not a function` in both Firefox (53) and Chromium (55).

[This demo](http://valums-file-uploader.github.io/file-uploader/) throws a similar error by the way, which is mentioned in [this issue](https://github.com/Valums-File-Uploader/file-uploader/issues/29).

**Comment by Jako** [comment]
Fixed with 1.5.4
