### ISSUE TITLE
MaxFiles not working en attachment not always correct

### ISSUE THREAD

**Issue by funkyduke** [Jako/AjaxUpload#18]
For some reason MaxFiles is not working. I can still upload more items then the number specified in MaxFiles. 

Also when using Formit for attachment when I upload f.e. 3 items I only get 2 or 1 attachment in the mail. But sometimes it's correct. Strange behaviour.

Modx last version 2.5.7. Browser I use for testing: Firefox last version. Windows 10.

**Comment by clsv** [comment]
Same problem, when i upload 2 file or more, i have bug, when update page or submit, sends one file, others disappears
