### ISSUE TITLE
Email Attachment

### ISSUE THREAD

**Issue by crecorn** [Jako/AjaxUpload#23]
I know this is vague but what reasons could prevent an image from not attaching to an email. I don't get any errors and don't know where to look. This is my formit setup:

```[[!FormIt?
&preHooks=`Formit2AjaxUpload`
&hooks=`recaptchav2,AjaxUpload2Formit,AjaxUploadAttachments,email,FormItAutoResponder,redirect`
&ajaxuploadFieldname=`image`
&ajaxuploadTarget=`../images/`
&ajaxuploadUid=`image`
&ajaxuploadAllowOverwrite=`true`
...
```

**Comment by Jako** [comment]
Maybe the attachment path is not valid here: https://github.com/Jako/AjaxUpload/blob/master/core/components/ajaxupload/elements/snippets/ajaxuploadattachments.snippet.php#L31

**Comment by Jako** [comment]
I close this issue for lack of response. Feel free to reopen the issue, if it is still valid.
