### ISSUE TITLE
[Q] question about using assets as uploaded files

### ISSUE THREAD

**Issue by zaigham** [Jako/AjaxUpload#26]
Is there a specific reason assets/ path is used for uploads, instead of some folder outside webroot or just php tmp folder? 

https://github.com/Jako/AjaxUpload/blob/29de0582b4d78479a5e6fbc16eab73baece530ab/core/components/ajaxupload/elements/snippets/ajaxuploadattachments.snippet.php#L15

**Comment by Jako** [comment]
That should be default path, where the handled image is located after ajaxUpload2Formit. It could be handled better. i.e. the file could be deleted after sending.
