### ISSUE TITLE
Modx 2.7.0 compatibility?

### ISSUE THREAD

**Issue by morelmm** [Jako/AjaxUpload#27]
AjaxUpload stopped working in modx 2.7.0, with this error log:
`[2018-12-12 11:29:36] (ERROR in modProcessor::run @ core/model/modx/modprocessor.class.php : 177) Flat file processor support is deprecated since version 2.7.0. `

**Comment by Jako** [comment]
Does it really don't work anymore? The error in the log is only a warning.

**Comment by morelmm** [comment]
Hi, thanks for quick reply,
yes, You're right, it is just a coincidence it stoped working right now, some server problem maybe
It's just a warning

Thanks :)

**Comment by Jako** [comment]
This will be fixed with the upcoming 1.5.7 version.
