### ISSUE TITLE
ajaxupload.cache_expires not working as expected

### ISSUE THREAD

**Issue by haeki1** [Jako/AjaxUpload#35]
Hi Thomas,

just discovered a minor bug regarding the cache_expires setting. On line 88 of ajaxupload.class.php the option is requested but its only requesting it from the snippet call, not from the systemssettings. 

`'cacheExpires' => intval($this->getOption('cacheExpires', $config, 4)),`

For example in formit2ajaxupload.snippet.php it is requested from the system settings:

`$scriptProperties['cacheExpires'] = $modx->getOption('ajaxuploadCacheExpires', $scriptProperties, $modx->getOption('ajaxupload.cache_expires', null, '4'));`

I don't know what ajaxuploadCacheExpires is for as ajaxupload.cache_expires seems to be the right one, but maybe some backwards compatibility. You will know it :-) But it somehow confused me as there is cacheExpires, ajaxuploadCacheExpires, ajaxupload.cache_expires for basically the same thing.

But long story short: If you change the setting inside the system settings and also when calling the snippet by &cacheExpires=`8760` for example everything works correct but I wouldn't expect, that I have to change it in two places to make it work correct.

Kind regards,
Fabian

**Comment by Jako** [comment]
Snippet properties will override the system settings. If both should use the same value, please use only the system setting.

**Comment by Jako** [comment]
The AJAX part of this extra can't use snippet properties.
