### ISSUE TITLE
Original image gets deleted when the form is sent a second time

### ISSUE THREAD

**Issue by haeki1** [Jako/AjaxUpload#36]
Hi Thomas,

I think its the desired behaviour but maybe there's an option to include a parameter to deactivate it. I ran into the problem as I am using ajaxupload for a raffle where users can send in their photos. In order to keep the server usage a bit lower I only allow one image each time the form is sent. But the user should be able to send the form multiple times and each time with a different image.

The only problem is, that the previous upload, whos path is written to the sessiondata, gets deleted in line 88 of AjaxUpload2Formit by „$ajaxUpload->deleteExisting();“. I guess the logic here was that a user who sends the form a second time is expected not to be happy with his first submit?

As that's not the case for my goal a short setting for the snippetcall would be nice. Just something like „deletePreviousSessionUpload“ or so.

Kind regards,
Fabian

**Comment by Jako** [comment]
If you don't want to have that side effect, you have to move the file with a custom hook after the AjaxUpload2Formit hook.
