### ISSUE TITLE
Problem with AjaxUpload

### ISSUE THREAD

**Issue by mot9igit** [Jako/AjaxUpload#4]
Hallo, Jako! I have problem with AjaxUpload. When I try to upload files, parameter fileid generated not correctly, it dublicated. If I upload 10 files, AjaxUpload upload 5 or 6 files.  Sorry, for my english. Attach screenshot:
![default](https://cloud.githubusercontent.com/assets/12006421/7215189/be68370a-e5e4-11e4-9ac5-f2ea8421a50a.PNG)

**Comment by Jako** [comment]
Did you solve that issue?

**Comment by Jako** [comment]
Should be fixed with AjaxUpload 1.5.0
