### ISSUE TITLE
Uploaded Filenames are not Random

### ISSUE THREAD

**Issue by pepebe** [Jako/AjaxUpload#41]
According to the docs, uploaded files automatically get random filenames:

> Uploaded files and generated thumbnails gets random filenames to avoid hotlinking uploaded not published files.

Source: https://jako.github.io/AjaxUpload/

As far as I can see filenames are NOT changed.

If this is not the default behavious, how can I force it? 

Regards,

pepebe

Quick Update: Apart from the missing random filename, everything is working fine. Files are uploaded to the expected place, and attachments are added to the outgloing mail. There are also no error messages or other problems.

I had a quick look at the snippets included and I could't find any code where a random filename would be generated.

**Comment by Jako** [comment]
Only the uploaded files of the ajax connector are renamed random. If the form is submitted, the files are named like the upload.
