### ISSUE TITLE
Empty file named "assets" attached

### ISSUE THREAD

**Issue by visuellemedien** [Jako/AjaxUpload#50]
When a form is sent without attaching a file, the email nevertheless shows an attachment file named "assets" with 0 Bytes in size. Some recipients might consider that as a harmful file. Is it possible to remove that?

**Comment by Jako** [comment]
Does this fix help?

**Comment by Jako** [comment]
I have tested the hook locally and cannot reproduce this. 

I have added a debug option to the AjaxUploadAttachment hook in 1.5.8, wich can be enabled by the ajaxupload.debug system setting or by the ajaxuploadDebug hook property. Maybe it is a not cleared queue after the form was submitted. If you can't solve it with that option, I can can offer paid support to solve this issue.
