### ISSUE TITLE
Generic error when uploading an image

### ISSUE THREAD

**Issue by sonicpunk** [Jako/AjaxUpload#51]
On our local environment, everything works as expected, but on the production server we are getting a generic error message written to the browser:

![Screenshot 2021-07-23 at 09 38 26](https://user-images.githubusercontent.com/447453/126751286-1b7f09c4-836d-42c2-be78-7bb0164c49ca.png)

When comparing the network activity, on the production server no thumbnail is being generated. Write permissions are granted on all related folders - the cache folder inside of the components/ajaxupload folder, plus the folder used in the snippet configuration.

No errors are being logged in the modx error log.

Both the local environment and production environments are running php 7.3. 

Any idea where we can look further?

**Comment by Jako** [comment]
The upload is handled here: https://github.com/Jako/AjaxUpload/blob/master/core/components/ajaxupload/processors/web/upload.class.php. Maybe you can add some MODX logging there to see, where/why it stops.

Is the target folder writable for PHP?

**Comment by sonicpunk** [comment]
The session is empty and therefore does not follow through with the script:

$_SESSION['ajaxupload']

**Comment by sonicpunk** [comment]
It seems that MODX needs to have anonymous_sessions set to true for this plugin to work. Is that in the documentation?

It is working now.

**Comment by Jako** [comment]
I have added some error logging for this in https://github.com/Jako/AjaxUpload/commit/50529c393335f52ee5e0cc50757229cf0aeb9eac
