### ISSUE TITLE
Multiple AjaxUpload calls on same page no longer working with 1.6.0

### ISSUE THREAD

**Issue by travisbotello** [Jako/AjaxUpload#52]
After upgrading to 1.6.0 having multiple AjaxUpload calls on the same page is no longer working. 

I compared to the output of 1.6.0 to the output of 1.5.8: the problem is caused by 1.6.0 only rendering JS code for one call while 1.5.8 was rendering a js block for every button with a different `&uid`.

This is the JS output for having two AjaxUpload calls on the same page:

1.5.8
![1.5.8](https://user-images.githubusercontent.com/1157380/148764109-9430a40a-713a-41d7-bc28-f329a95c0f8e.png)
 
1.6.0
![1.6.0](https://user-images.githubusercontent.com/1157380/148764318-652d448d-81d1-4a57-bc0f-c4e276010a6c.png)

These are the calls I am using:

```
[[!AjaxUpload?
    &uid=`cv`
    &allowedExtensions=`jpg,jpeg,png,gif,pdf`
    &thumbX=`75`
    &thumbY=`75`
    &maxFiles=`1`
]]

[[!AjaxUpload?
    &uid=`cl`
    &allowedExtensions=`jpg,jpeg,png,gif,pdf`
    &thumbX=`75`
    &thumbY=`75`
    &maxFiles=`1`
]]
```

**Comment by Jako** [comment]
It is fully fixed with https://github.com/Jako/AjaxUpload/commit/dcb865cec1f430b3543a96409de1703ced791433.

**Comment by travisbotello** [comment]
Thanks for the quick fix. It is working again!!

**Comment by Jako** [comment]
A new version is available. Thanks for the bug report.

**Comment by Jako** [comment]
Just for curiosity: Did you solve the issue with two queues in the hooks?

**Comment by travisbotello** [comment]
I am submitting each `AjaxUpload` call via AJAX to this `FormIt` call separately and then using a custom hook in the actual form submission to get the files from the session and attach those to the email.

```
[[!FormIt?
    &hooks=`AjaxUpload2Formit,AjaxUpload2Session`
    &ajaxuploadFieldname=`[[!#POST.field_name]]`
    &ajaxuploadUid=`[[!#POST.field_name]]`
    &ajaxuploadClearQueue=`1`
    &ajaxuploadTarget=`image-cache/uploads`
    &successMessage=`{"success": "true", "message": ""}`
    &validationErrorMessage=`{"success": "false", "message": "Fehler! Bitte versuchen Sie es erneut!"}`
    &errTpl=`{"success": "false", "message": "[[+error]]"}`
    &validate=`file_id:required`
]]
```

Custom Formit hook for getting files from session
```
$hook->modx->getService('mail', 'mail.modPHPMailer');

foreach ($_SESSION['files'] as $cats) {
    foreach ($cats as $file) {
        $hook->modx->mail->mailer->AddAttachment($file);
    }
}

return true;
```

So workflow on form submission is:
- ajax call formit for each upload queue and store in session
- custom formit hook to get all files from session and attach to mail
- submit the form

That way I can also validate each upload field separately before submitting the actual form

**Comment by Jako** [comment]
ok, thats possible but … phew :-)

**Comment by travisbotello** [comment]
Client requests... ;)
