### ISSUE TITLE
found some error when pressed the delete button.

### ISSUE THREAD

**Issue by oleang** [Jako/AjaxUpload#56]
I found some Error when I pressed the delete button on the top right. The uploaded file cannot be deleted and an error occurs in the console as shown in the attached image.
![Screenshot (154)](https://user-images.githubusercontent.com/142615/191451861-5fba8330-fbe2-4c67-adb8-5e3d708926f8.png)

**Comment by Jako** [comment]
Thanks for the error report. This is fixed with version 1.6.3.
