### ISSUE TITLE
Error after installing AjaxUpload - array_key_exists

### ISSUE THREAD

**Issue by nick2687** [Jako/AjaxUpload#6]
I've just installed this on a site and when attempting use the very basic snippet example you provide on the documentation site:

```
[[!AjaxUpload?
&uid=`image`
&allowedExtensions=`jpg,jpeg,png,gif`
&thumbX=`75`
&thumbY=`75`
]]
```

I receive the following error in the Modx error logs.

```
[2016-08-07 10:56:31] (ERROR @ /paas/c2064/www/core/components/ajaxupload/model/ajaxupload/ajaxupload.class.php : 108) PHP warning: array_key_exists() expects parameter 2 to be array, null given
[2016-08-07 10:56:31] (ERROR @ /paas/c2064/www/core/components/ajaxupload/model/ajaxupload/ajaxupload.class.php : 108) PHP warning: array_key_exists() expects parameter 2 to be array, null given
```

I'm using Modx version 2.5.1 & php version 5.6.20

Have you seen this before?

**Comment by nick2687** [comment]
Figured it out... Seems this was a jquery issue, had to include the jquery script at the bottom of the site even though I had already included jquery in the head...

**Comment by Jako** [comment]
When does this warning occur. During displaying the upload form or during uploading a file?

**Comment by nick2687** [comment]
When displaying the upload form.

**Comment by Izacktly** [comment]
For me this also happens upon loading the form.  Three instances of the error message is output.
Also when I attempt to upload a file, the error also occurs.  Five instances of the error message is ouput upon upload.

**Comment by Izacktly** [comment]
Also tested the delete all button and this also generates the error

**Comment by Jako** [comment]
Please try the patch above. It should fix the warning.

**Comment by Izacktly** [comment]
Awesome Jako!, this seemed to have fixed the issue thus far.  Thanks so much for your support.  This addon is extremely useful.  Thanks again!
