### ISSUE TITLE
Default lexicon entry is not set with formit hook AjaxUploadRequired

### ISSUE THREAD

**Issue by travisbotello** [Jako/AjaxUpload#62]
I am currently testing the `AjaxUploadRequired` hook with formit. Per documentation I'd expect the default lexicon entry to render as the error message when no file is uploaded. 

The form is not being submitted, but the error message is not being rendered. 

I have to manually specify `&ajaxuploadRequiredMessage` to display an error message. Maybe there's some glitch.

Thanks in advance!

**Comment by Jako** [comment]
Can you check, if this is solved with the patch?

**Comment by travisbotello** [comment]
> Can you check, if this is solved with the patch?

Fixed :)
