### ISSUE TITLE
Unique ID question

### ISSUE THREAD

**Issue by crecorn** [Jako/AjaxUpload#9]
I'm not clear on how this works. Maybe I'm expecting it to work in the wrong way.

I have an order being placed with a PO number, I'd like to either amend the file name or create a unique folder for the image.  Is this possible?

**Comment by Jako** [comment]
Generating an unique name with own options is not possible with the AjaxUpload2Formit hook. All files are saved with an unique name per default (could be disabled by setting `allowOverwrite` to true).

Do rename the files, you could create and use an own hook after AjaxUpload2Formit.

**Comment by crecorn** [comment]
The names of the files I upload are not changed to a unique name???

**Comment by Jako** [comment]
Really? Are you able to debug that?

The renaming should happen here: https://github.com/Jako/AjaxUpload/blob/master/core/components/ajaxupload/model/ajaxupload/ajaxupload.class.php#L361-L368
